/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://oss.sonatype.org/content/repositories/snapshots")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api("com.google.code.gson:gson:2.8.6")
    api("org.slf4j:slf4j-api:1.7.25")
    api("org.apache.logging.log4j:log4j-api:2.7")
    api("org.apache.logging.log4j:log4j-core:2.7")
    api("org.apache.logging.log4j:log4j-slf4j-impl:2.7")
    api("org.java-websocket:Java-WebSocket:1.5.1")
}

group = "com.github.realzimboguy.ewelink.api"
version = "2.1.2-RELEASE"
description = "ewelink-api-java"
java.sourceCompatibility = JavaVersion.VERSION_1_8

java {
    withSourcesJar()
    withJavadocJar()
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
